apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: backend
  labels:
    app: backend
spec:
  selector:
    app: backend
  ports:
    - name: http
      port: 80
      targetPort: 8080
  type: ClusterIP # only accessible inside the cluster. No external access. Frontend calls backend through this service.
                  # traffic never leaves the cluster. Istio intercepts it and enforces mTLS automatically.